package com.fuzzybat23.ddoors;


import com.fuzzybat23.ddoors.proxy.CommonProxy;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@net.minecraftforge.fml.common.Mod(modid = "ddoors", version = "1.0", clientSideOnly = true, acceptedMinecraftVersions = "[1.12, 1.13]" )
public class DoubleDoors
{
    @net.minecraftforge.fml.common.Mod.Instance("DoubleDoors")
    public static final String MODID = "ddoors";

    public static final String CLIENT_SIDE_PROXY = "com.fuzzybat23.ddoors.proxy.ClientProxy";
    public static final String CLIENT_SERVER_PROXY = "com.fuzzybat23.ddoors.proxy.ServerProxy";

    @Mod.Instance
    public static DoubleDoors instance;

    @SidedProxy(clientSide = CLIENT_SIDE_PROXY, serverSide = CLIENT_SERVER_PROXY)
    public static CommonProxy proxy;

    @Mod.EventHandler
    @SideOnly(Side.CLIENT)
    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.version = "1.0";
        data.name = "Double Doors";
        data.description = "Allows side by side doors to open at the same time.";
        data.authorList.add("Fuzzybat23");
        data.url="https://minecraft.curseforge.com/members/fuzzybat23/projects";
        data.credits = "All me this time, baby! :D But seriously, still with lots of forum help at Minecraft Forge Forums. :)";
        data.logoFile = "assets/logo/ddoors.png";

        proxy.registerTickHandler();
        MinecraftForge.EVENT_BUS.register(this);
    }
}