package com.fuzzybat23.ddoors;


import com.fuzzybat23.ddoors.proxy.CommonProxy;

import net.minecraft.block.Block;
import net.minecraft.block.state.IBlockState;
import net.minecraft.entity.player.EntityPlayer;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.entity.player.PlayerInteractEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import static com.fuzzybat23.ddoors.WoodenDoor.*;

@net.minecraftforge.fml.common.Mod(modid = "ddoors", version = "1.0", clientSideOnly = true, acceptedMinecraftVersions = "[1.12, 1.13]" )
public class DoubleDoors
{
    @net.minecraftforge.fml.common.Mod.Instance("DoubleDoors")
    public static final String MODID = "ddoors";

    public static final String CLIENT_SIDE_PROXY = "com.fuzzybat23.ddoors.proxy.ClientProxy";
    public static final String CLIENT_SERVER_PROXY = "com.fuzzybat23.ddoors.proxy.ServerProxy";

    public static final Logger logger = LogManager.getLogger();

    @Mod.Instance
    public static DoubleDoors instance;

    @SidedProxy(clientSide = CLIENT_SIDE_PROXY, serverSide = CLIENT_SERVER_PROXY)
    public static CommonProxy proxy;

    @Mod.EventHandler
    @SideOnly(Side.CLIENT)
    public void preInit(FMLPreInitializationEvent event)
    {
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.version = "1.0";
        data.name = "Double Doors";
        data.description = "Allows side by side doors to open at the same time.";
        data.authorList.add("Fuzzybat23");
        data.url="https://minecraft.curseforge.com/members/fuzzybat23/projects";
        data.credits = "All me this time, baby! :D But seriously, still with lots of forum help at Minecraft Forge Forums. :)";
        data.logoFile = "assets/logo/ddoors.png";

        proxy.registerTickHandler();
        MinecraftForge.EVENT_BUS.register(this);
    }

    @SubscribeEvent
    public void onBlockInteract(PlayerInteractEvent.RightClickBlock event)
    {
        EntityPlayer player = event.getEntityPlayer();
        BlockPos pos = event.getPos();
        Block block = event.getWorld().getBlockState(event.getPos()).getBlock();
        IBlockState state = event.getWorld().getBlockState(pos);
        World world = event.getWorld();

        if( isWoodenDoor(block, state))
        {
            logger.info("state.getBlock() = " + state.getBlock().toString());
            checkForDoors(world, state, pos);
        }
    }
}